(() => {
  const en = {
    meta: "Dungeon 9999m — fight, loot, and descend through a dungeon measured one dangerous meter at a time.",
    "nav.descent": "The descent", "nav.combat": "Combat", "nav.qa": "Developer Q&A", "nav.store": "App Store",
    "hero.line": "One dungeon. One depth record.<br>No easy way back.", "hero.body": "Fight through torchlit halls, break enemy packs, claim what they drop, and push the descent one dangerous meter farther.", "hero.cta": "Download on the App Store", "hero.meta": "Portrait action RPG · iPhone", "hero.depth": "The princess waits below.", "hero.live": "REAL GAMEPLAY",
    "descent.title": "Every meter changes the odds.", "descent.body": "The dungeon is a chain of stone chambers suspended over a bottomless void. Search the edges, read the next room, and decide whether your supplies can carry you deeper.",
    "shot1.title": "Search the dark", "shot1.body": "Rooms hide weapons, chests, and the route downward.", "shot2.title": "Keep the streak alive", "shot2.body": "Control the room before the pack controls you.", "shot3.title": "Survive the pack", "shot3.body": "Position, timing, and supplies decide every fight.",
    "combat.title": "Fight. Loot.<br>Descend.", "combat.body": "Dungeon 9999m keeps the loop visible at all times: current depth, deepest record, health, magic, supplies, currency, and the distance still separating you from the bottom.",
    "combat.one.title": "Read the room", "combat.one.body": "Use the open floor, corners, and narrow passages to manage groups instead of trading hits.", "combat.two.title": "Claim the drop", "combat.two.body": "Weapons and resources appear inside the dungeon. What you find changes how the next rooms play.", "combat.three.title": "Push the record", "combat.three.body": "Your current depth may end. Your deepest record remains the challenge waiting for the next descent.",
    statement: "The goal is simple to understand.<br><b>Reaching it is not.</b>",
    "qa.title": "Before you descend.", "qa.intro": "A short briefing from the developer.", "qa.q1": "What kind of game is Dungeon 9999m?", "qa.a1": "A portrait-format action RPG about fighting through an enormous dungeon and pushing your deepest record toward 9,999 meters.", "qa.q2": "What do I do during a descent?", "qa.a2": "Explore rooms, fight enemy groups, maintain kill streaks, collect weapon drops, manage potions, and keep moving deeper.", "qa.q3": "What makes progress visible?", "qa.a3": "The interface tracks your current depth, deepest record, remaining distance, level, health, magic, resources, and currency throughout the run.", "qa.q4": "Where can I play it?", "qa.a4": "Dungeon 9999m is currently available for iPhone through the App Store.",
    "final.line": "How deep can you go?", "final.cta": "Begin the descent", "footer.privacy": "Privacy Policy", "footer.support": "Game Support", "footer.store": "View on the App Store"
  };

  const translations = {
    en,
    es: {
      ...en, meta: "Dungeon 9999m — lucha, saquea y desciende por una mazmorra medida metro a metro.", "nav.descent": "El descenso", "nav.combat": "Combate", "nav.qa": "Preguntas al desarrollador", "hero.line": "Una mazmorra. Un récord de profundidad.<br>No hay una salida fácil.", "hero.body": "Lucha en pasillos iluminados por antorchas, rompe las manadas enemigas, reclama su botín y desciende un metro peligroso más.", "hero.cta": "Descargar en App Store", "hero.meta": "RPG de acción vertical · iPhone", "hero.depth": "La princesa espera abajo.", "hero.live": "JUEGO REAL", "descent.title": "Cada metro cambia las probabilidades.", "descent.body": "La mazmorra es una cadena de cámaras de piedra suspendidas sobre un vacío sin fondo. Explora los bordes, estudia la siguiente sala y decide si tus suministros te permitirán seguir.", "shot1.title": "Explora la oscuridad", "shot1.body": "Las salas esconden armas, cofres y el camino hacia abajo.", "shot2.title": "Mantén la racha", "shot2.body": "Controla la sala antes de que la manada te controle.", "shot3.title": "Sobrevive a la manada", "shot3.body": "La posición, el momento y los suministros deciden cada combate.", "combat.title": "Lucha. Saquea.<br>Desciende.", "combat.body": "Dungeon 9999m mantiene siempre visible el ciclo: profundidad actual, récord, salud, magia, suministros, monedas y la distancia restante.", "combat.one.title": "Lee la sala", "combat.one.body": "Usa el espacio, las esquinas y los pasos estrechos para controlar grupos.", "combat.two.title": "Reclama el botín", "combat.two.body": "Las armas y recursos aparecen dentro de la mazmorra y cambian las siguientes salas.", "combat.three.title": "Supera tu récord", "combat.three.body": "El descenso puede terminar, pero tu récord seguirá esperándote la próxima vez.", statement: "El objetivo es fácil de entender.<br><b>Alcanzarlo no.</b>", "qa.title": "Antes de descender.", "qa.intro": "Un breve informe del desarrollador.", "qa.q1": "¿Qué tipo de juego es Dungeon 9999m?", "qa.a1": "Un RPG de acción vertical en el que luchas por una enorme mazmorra y acercas tu récord a los 9.999 metros.", "qa.q2": "¿Qué hago durante un descenso?", "qa.a2": "Explora, combate grupos enemigos, mantén rachas, recoge armas, administra pociones y sigue bajando.", "qa.q3": "¿Cómo se muestra el progreso?", "qa.a3": "La interfaz muestra profundidad actual, récord, distancia restante, nivel, salud, magia, recursos y monedas.", "qa.q4": "¿Dónde puedo jugar?", "qa.a4": "Dungeon 9999m está disponible actualmente para iPhone en App Store.", "final.line": "¿Hasta dónde puedes llegar?", "final.cta": "Iniciar el descenso", "footer.privacy": "Política de privacidad", "footer.support": "Soporte", "footer.store": "Ver en App Store"
    },
    "zh-hant": {
      ...en, meta: "Dungeon 9999m——戰鬥、搜刮，在以每一米衡量危險的地下城持續深入。", "nav.descent": "深入地下", "nav.combat": "戰鬥", "nav.qa": "開發者問答", "hero.line": "一座地下城。一項深度紀錄。<br>沒有輕鬆的退路。", "hero.body": "穿過火炬照亮的長廊，擊潰成群敵人，收下戰利品，再向危險深處推進一米。", "hero.cta": "前往 App Store 下載", "hero.meta": "直向動作角色扮演 · iPhone", "hero.depth": "公主正在下方等待。", "hero.live": "真實遊戲畫面", "descent.title": "每深入一米，勝算都會改變。", "descent.body": "地下城由懸在無底深淵上的石造房間串聯而成。搜索邊緣、判讀下一個房間，衡量補給是否足以讓你繼續深入。", "shot1.title": "搜索黑暗", "shot1.body": "房間裡藏著武器、寶箱和通往下方的道路。", "shot2.title": "維持連續擊殺", "shot2.body": "在獸群控制你之前，先控制整個房間。", "shot3.title": "從獸群中生還", "shot3.body": "走位、時機與補給決定每一場戰鬥。", "combat.title": "戰鬥。搜刮。<br>深入。", "combat.body": "Dungeon 9999m 始終讓循環清楚可見：目前深度、最深紀錄、生命、魔力、補給、貨幣，以及你離最深處還有多遠。", "combat.one.title": "判讀房間", "combat.one.body": "利用開闊地面、轉角和狹窄通道管理敵群，而不是正面換血。", "combat.two.title": "取得掉落", "combat.two.body": "武器與資源會出現在地下城內，你找到的物品將改變接下來的戰鬥。", "combat.three.title": "突破紀錄", "combat.three.body": "本次深入可能結束，但最深紀錄會成為下一次挑戰。", statement: "目標很容易理解。<br><b>抵達卻不容易。</b>", "qa.title": "深入之前。", "qa.intro": "來自開發者的簡短說明。", "qa.q1": "Dungeon 9999m 是什麼類型的遊戲？", "qa.a1": "一款直向動作角色扮演遊戲。你要在龐大地下城戰鬥，將最深紀錄逐步推向 9,999 米。", "qa.q2": "深入地下時要做什麼？", "qa.a2": "探索房間、迎戰敵群、維持連續擊殺、收集武器掉落、管理藥水並繼續深入。", "qa.q3": "遊戲如何顯示進度？", "qa.a3": "介面會持續顯示目前深度、最深紀錄、剩餘距離、等級、生命、魔力、資源與貨幣。", "qa.q4": "可以在哪裡遊玩？", "qa.a4": "Dungeon 9999m 目前已在 App Store 推出 iPhone 版本。", "final.line": "你能深入多遠？", "final.cta": "開始深入", "footer.privacy": "隱私權政策", "footer.support": "遊戲支援", "footer.store": "前往 App Store"
    },
    ja: {
      ...en, meta: "Dungeon 9999m——戦い、拾い、危険な一メートルずつダンジョンを下れ。", "nav.descent": "深層へ", "nav.combat": "戦闘", "nav.qa": "開発者Q&A", "hero.line": "ひとつのダンジョン。ひとつの深度記録。<br>楽な帰り道はない。", "hero.body": "松明が照らす回廊で敵の群れを破り、戦利品を手に入れ、危険な一メートル先へ進め。", "hero.cta": "App Storeでダウンロード", "hero.meta": "縦画面アクションRPG · iPhone", "hero.depth": "姫は下で待っている。", "hero.live": "実際のゲームプレイ", "descent.title": "一メートルごとに、状況が変わる。", "descent.body": "底なしの闇に浮かぶ石造りの部屋。その隅々を探り、次の部屋を読み、手持ちの物資でさらに下れるか判断しよう。", "shot1.title": "闇を探れ", "shot1.body": "部屋には武器、宝箱、そして下への道が隠されている。", "shot2.title": "連続撃破をつなげ", "shot2.body": "群れに支配される前に、部屋を制圧せよ。", "shot3.title": "群れを生き延びろ", "shot3.body": "位置取り、タイミング、物資が勝敗を決める。", "combat.title": "戦え。拾え。<br>下れ。", "combat.body": "Dungeon 9999mでは、現在深度、最深記録、体力、魔力、物資、通貨、最深部までの距離が常に表示される。", "combat.one.title": "部屋を読め", "combat.one.body": "開けた場所、角、狭い通路を使い、正面から殴り合わず敵群を管理しよう。", "combat.two.title": "戦利品を得ろ", "combat.two.body": "武器や資源はダンジョン内で見つかり、次の部屋での戦い方を変える。", "combat.three.title": "記録を更新せよ", "combat.three.body": "今回の探索が終わっても、最深記録は次の挑戦を待っている。", statement: "目標は単純だ。<br><b>到達は、単純ではない。</b>", "qa.title": "下る前に。", "qa.intro": "開発者からの短い説明です。", "qa.q1": "Dungeon 9999mはどんなゲームですか？", "qa.a1": "巨大なダンジョンを戦いながら下り、最深記録を9,999メートルへ近づける縦画面アクションRPGです。", "qa.q2": "探索中は何をしますか？", "qa.a2": "部屋を探索し、敵群と戦い、連続撃破を維持し、武器を拾い、ポーションを管理しながら下ります。", "qa.q3": "進行状況はどう表示されますか？", "qa.a3": "現在深度、最深記録、残り距離、レベル、体力、魔力、資源、通貨が常に表示されます。", "qa.q4": "どこで遊べますか？", "qa.a4": "Dungeon 9999mは現在、iPhone向けにApp Storeで配信されています。", "final.line": "どこまで下れる？", "final.cta": "探索を始める", "footer.privacy": "プライバシーポリシー", "footer.support": "ゲームサポート", "footer.store": "App Storeで見る"
    },
    ko: {
      ...en, meta: "Dungeon 9999m — 싸우고, 전리품을 얻고, 위험한 1미터씩 던전을 내려가세요.", "nav.descent": "심층으로", "nav.combat": "전투", "nav.qa": "개발자 Q&A", "hero.line": "하나의 던전. 하나의 깊이 기록.<br>쉬운 귀환은 없다.", "hero.body": "횃불이 밝히는 복도에서 적 무리를 무너뜨리고 전리품을 챙긴 뒤, 위험한 1미터를 더 내려가세요.", "hero.cta": "App Store에서 다운로드", "hero.meta": "세로형 액션 RPG · iPhone", "hero.depth": "공주는 아래에서 기다린다.", "hero.live": "실제 게임플레이", "descent.title": "1미터마다 승산이 달라진다.", "descent.body": "던전은 끝없는 심연 위에 떠 있는 석조 방들로 이어집니다. 가장자리를 수색하고 다음 방을 읽으며 보급품으로 더 내려갈 수 있을지 판단하세요.", "shot1.title": "어둠을 수색하라", "shot1.body": "방에는 무기, 상자, 아래로 향하는 길이 숨어 있습니다.", "shot2.title": "연속 처치를 이어라", "shot2.body": "무리가 당신을 지배하기 전에 방을 장악하세요.", "shot3.title": "무리에서 살아남아라", "shot3.body": "위치, 타이밍, 보급품이 매 전투를 결정합니다.", "combat.title": "싸워라. 얻어라.<br>내려가라.", "combat.body": "Dungeon 9999m은 현재 깊이, 최고 기록, 체력, 마력, 보급품, 재화, 최하층까지 남은 거리를 언제나 보여 줍니다.", "combat.one.title": "방을 읽어라", "combat.one.body": "정면으로 피해를 주고받기보다 열린 공간과 모서리, 좁은 통로로 적 무리를 관리하세요.", "combat.two.title": "전리품을 차지하라", "combat.two.body": "무기와 자원은 던전 안에서 발견되며 다음 방의 전투 방식을 바꿉니다.", "combat.three.title": "기록을 밀어 올려라", "combat.three.body": "이번 하강은 끝나도 최고 깊이는 다음 도전을 기다립니다.", statement: "목표는 이해하기 쉽다.<br><b>도달하기는 어렵다.</b>", "qa.title": "내려가기 전에.", "qa.intro": "개발자가 전하는 짧은 안내입니다.", "qa.q1": "Dungeon 9999m은 어떤 게임인가요?", "qa.a1": "거대한 던전에서 싸우며 최고 깊이를 9,999미터까지 밀어 올리는 세로형 액션 RPG입니다.", "qa.q2": "하강 중에는 무엇을 하나요?", "qa.a2": "방을 탐색하고 적 무리와 싸우며 연속 처치를 유지하고 무기를 줍고 물약을 관리하면서 계속 내려갑니다.", "qa.q3": "진행 상황은 어떻게 보이나요?", "qa.a3": "현재 깊이, 최고 기록, 남은 거리, 레벨, 체력, 마력, 자원, 재화가 계속 표시됩니다.", "qa.q4": "어디에서 플레이할 수 있나요?", "qa.a4": "Dungeon 9999m은 현재 iPhone용으로 App Store에서 제공됩니다.", "final.line": "얼마나 깊이 내려갈 수 있습니까?", "final.cta": "하강 시작", "footer.privacy": "개인정보 처리방침", "footer.support": "게임 지원", "footer.store": "App Store에서 보기"
    },
    "zh-hans": {
      ...en, meta: "Dungeon 9999m——战斗、搜刮，在以每一米衡量危险的地下城不断深入。", "nav.descent": "深入地下", "nav.combat": "战斗", "nav.qa": "开发者问答", "hero.line": "一座地下城。一项深度纪录。<br>没有轻松的退路。", "hero.body": "穿过火炬照亮的长廊，击溃成群敌人，收下战利品，再向危险深处推进一米。", "hero.cta": "前往 App Store 下载", "hero.meta": "竖屏动作角色扮演 · iPhone", "hero.depth": "公主正在下方等待。", "hero.live": "真实游戏画面", "descent.title": "每深入一米，胜算都会改变。", "descent.body": "地下城由悬在无底深渊上的石造房间串联而成。搜索边缘、判断下一个房间，衡量补给是否足够让你继续深入。", "shot1.title": "搜索黑暗", "shot1.body": "房间里藏着武器、宝箱和通往下方的道路。", "shot2.title": "维持连续击杀", "shot2.body": "在兽群控制你之前，先控制整个房间。", "shot3.title": "从兽群中生还", "shot3.body": "走位、时机与补给决定每一场战斗。", "combat.title": "战斗。搜刮。<br>深入。", "combat.body": "Dungeon 9999m 始终让循环清楚可见：当前深度、最深纪录、生命、魔力、补给、货币，以及你离最深处还有多远。", "combat.one.title": "判断房间", "combat.one.body": "利用开阔地面、转角和狭窄通道管理敌群，而不是正面换血。", "combat.two.title": "取得掉落", "combat.two.body": "武器和资源会出现在地下城内，你找到的物品将改变接下来的战斗。", "combat.three.title": "突破纪录", "combat.three.body": "本次深入可能结束，但最深纪录会成为下一次挑战。", statement: "目标很容易理解。<br><b>抵达却不容易。</b>", "qa.title": "深入之前。", "qa.intro": "来自开发者的简短说明。", "qa.q1": "Dungeon 9999m 是什么类型的游戏？", "qa.a1": "一款竖屏动作角色扮演游戏。你要在庞大地下城战斗，将最深纪录逐步推向 9,999 米。", "qa.q2": "深入地下时要做什么？", "qa.a2": "探索房间、迎战敌群、维持连续击杀、收集武器掉落、管理药水并继续深入。", "qa.q3": "游戏如何显示进度？", "qa.a3": "界面会持续显示当前深度、最深纪录、剩余距离、等级、生命、魔力、资源与货币。", "qa.q4": "可以在哪里游玩？", "qa.a4": "Dungeon 9999m 目前已在 App Store 推出 iPhone 版本。", "final.line": "你能深入多远？", "final.cta": "开始深入", "footer.privacy": "隐私政策", "footer.support": "游戏支持", "footer.store": "前往 App Store"
    }
  };

  const supported = ["en", "es", "zh-hant", "ja", "ko", "zh-hans"];
  const requested = new URLSearchParams(window.location.search).get("lang")?.toLowerCase() || "en";
  const language = supported.includes(requested) ? requested : "en";
  const htmlLanguages = { en: "en", es: "es", "zh-hant": "zh-Hant", ja: "ja", ko: "ko", "zh-hans": "zh-Hans" };
  const pageLanguages = { en: "english", es: "spanish", "zh-hant": "traditional-chinese", ja: "japanese", ko: "korean", "zh-hans": "chinese" };

  document.documentElement.lang = htmlLanguages[language];
  document.querySelectorAll("[data-lang]").forEach((link) => {
    if (link.dataset.lang === language) link.setAttribute("aria-current", "page");
  });

  const dictionary = translations[language];
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = dictionary[element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  const description = document.querySelector('meta[name="description"]');
  if (description) description.setAttribute("content", dictionary.meta);
  const policyLink = document.querySelector("[data-policy-link]");
  if (policyLink) policyLink.href = `index.html#${pageLanguages[language]}`;
  const supportLink = document.querySelector("[data-support-link]");
  if (supportLink) supportLink.href = `support.html#${pageLanguages[language]}`;
})();
